### PR TITLE
fixing a few threadpool errors that were found

### PR DESCRIPTION
**Pull request by jebrando**

### CODE REVIEW

**Comment by anporumb** [comment]
> EXECUTION_ENGINE_HANDLE execution_engine_create(void* execution_engine_parameters);

errr... shouldn't these function be called with "real_"?

Here and everywhere.

---
Refers to: linux/linux_reals/real_execution_engine.h:33 in 152385c. [](commit_id = 152385ca8ee493f7d5c8a26ac9f4c5b2f924c3a0, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
> void execution_engine_dec_ref(EXECUTION_ENGINE_HANDLE execution_engine);

real_
Wow, how did it work?
Shouldn't Parth's lib check have failed here?

---
Refers to: linux/linux_reals/real_execution_engine.h:34 in 152385c. [](commit_id = 152385ca8ee493f7d5c8a26ac9f4c5b2f924c3a0, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
> SRW_LOCK_HANDLE srw_lock_create(bool do_statistics, const char* lock_name);

real_ here too

---
Refers to: linux/linux_reals/real_srw_lock.h:37 in 152385c. [](commit_id = 152385ca8ee493f7d5c8a26ac9f4c5b2f924c3a0, deletion_comment = False)

**Review by dcristoloveanu — APPROVED** [review]
:shipit:

**Pull request merged**
