### PR TITLE
Remove WaitOnAddress log spam

### PR DESCRIPTION
**Pull request by mattdurak**
timeout is a common error, this is spamming logs in some places

### CODE REVIEW

**Review by jebrando — APPROVED** [review]

**Comment by anporumb** [comment]
>             LogError("failure in WaitOnAddress(address=%p, &compare_value=%p, address_size=%zu, timeout_ms=%" PRId32 ")",

Is LogLastError available here?

---
Refers to: c_pal_ll/win32/src/sync_win32.c:30 in 6cc4a81. [](commit_id = 6cc4a81f03dfce90a6ab1575c4947773c78cfd8f, deletion_comment = False)

**Comment by anporumb** [comment]
> #include "windows.h"

should come before "our" headers.

---
Refers to: c_pal_ll/win32/src/sync_win32.c:10 in 6cc4a81. [](commit_id = 6cc4a81f03dfce90a6ab1575c4947773c78cfd8f, deletion_comment = False)

**Comment by mattdurak** [comment]
>             LogError("failure in WaitOnAddress(address=%p, &compare_value=%p, address_size=%zu, timeout_ms=%" PRId32 ")",

seems like it comes from c_logging, so yes, replacing with that now

---
In reply to: [1412659103](https://github.com/Azure/c-pal/pull/214#issuecomment-1412659103) [](http://example.com/codeflow?ancestors=1412659103,1412659103)

---
Refers to: c_pal_ll/win32/src/sync_win32.c:30 in 6cc4a81. [](commit_id = 6cc4a81f03dfce90a6ab1575c4947773c78cfd8f, deletion_comment = False)

**Comment by anporumb** [comment]
>             LogError("failure in WaitOnAddress(address=%p, &compare_value=%p, address_size=%zu, timeout_ms=%" PRId32 ")",

And since timeout_ms is uint32_t, shouldn't this format speicifier be PRIu32?

I suspect it will start printing negative numbers with big enough timeout_ms number.

---
Refers to: c_pal_ll/win32/src/sync_win32.c:30 in 6cc4a81. [](commit_id = 6cc4a81f03dfce90a6ab1575c4947773c78cfd8f, deletion_comment = False)

**Comment by mattdurak** [comment]
> #include "windows.h"

moved

---
In reply to: [1412660865](https://github.com/Azure/c-pal/pull/214#issuecomment-1412660865) [](http://example.com/codeflow?ancestors=1412660865,1412660865)

---
Refers to: c_pal_ll/win32/src/sync_win32.c:10 in 6cc4a81. [](commit_id = 6cc4a81f03dfce90a6ab1575c4947773c78cfd8f, deletion_comment = False)

**Comment by mattdurak** [comment]
>             LogError("failure in WaitOnAddress(address=%p, &compare_value=%p, address_size=%zu, timeout_ms=%" PRId32 ")",

yes, changed

---
In reply to: [1412663085](https://github.com/Azure/c-pal/pull/214#issuecomment-1412663085) [](http://example.com/codeflow?ancestors=1412663085,1412663085)

---
Refers to: c_pal_ll/win32/src/sync_win32.c:30 in 6cc4a81. [](commit_id = 6cc4a81f03dfce90a6ab1575c4947773c78cfd8f, deletion_comment = False)

**Pull request merged**
